#+title: README
#+author: Christian Elliott
#+email: cdelliott96@gmail.com

* mpf
TODO: Describe this project

Welcome to your new gem! In this directory, you'll find the files you need to be
able to package up your Ruby library into a gem. Put your Ruby code in the file
=lib/mpf=. To experiment with that code, run =bin/console= for an interactive
prompt.
** Installation
TODO: Replace `UPDATE_WITH_YOUR_GEM_NAME_PRIOR_TO_RELEASE_TO_RUBYGEMS_ORG` with
your gem name right after releasing it to RubyGems.org. Please do not do it
earlier due to security reasons. Alternatively, replace this section with
instructions to install your gem from git if you don't plan to release to
RubyGems.org.

Install the gem and add to the application's Gemfile by executing:

#+begin_src
bundle add GEM_NAME_HERE
#+end_src

If bundler is not being used to manage dependencies, install the gem by
executing:

#+begin_src
gem install GEM_NAME_HERE
#+end_src
** Usage
TODO: Write usage instructions here
** Docker setup
If you'd like to update the Gemfile.lock, first remove it: =rm Gemfile.lock=.

Then, create a dummy container: =docker create --name mpf mpf=.

Then use =docker cp= to move the file from the container to the local
filesystem: =docker cp mpf:Gemfile.lock .=

Then, finally, remove the running container:
=docker rm -f mpf=
*** Updated method from [[https://hub.docker.com/_/ruby][Ruby Docker image]]
=docker run --rm -v ./:/mpf -w /mpf ruby:3.3.0-alpine bundle install=
** Development
After checking out the repo, run =bin/setup= to install dependencies. Then, run
=rake spec= to run the tests. You can also run =bin/console= for an interactive
prompt that will allow you to experiment.

To install this gem onto your local machine, run =bundle exec rake install=. To
release a new version, update the version number in =version.rb=, and then run
=bundle exec rake release=, which will create a git tag for the version, push
git commits and the created tag, and push the =.gem= file to [[https://rubygems.org][rubygems.org]].
** Contributing
Bug reports and pull requests are welcome on GitHub at
[[https://github.com/c-elliott96/mpf]].
